=== ReVanced/revanced-discord-bot/configuration.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "https://github.com/ReVancedTeam/revanced-signatures/blob/main/signatures.schema.json",
	"title": "Configuration schema",
	"description": "The Revanced Discord bot configuration schema.",
	"type": "object",
	"properties": {
		"general": {
			"type": "object",
			"properties": {
				"embed_color": {
					"$ref": "#/$defs/color"
				},
				"mute": {
					"type": "object",
					"properties": {
						"role": {
							"type": "integer",
							"description": "The id of the role."
						},
						"take": {
							"$ref": "#/$defs/roles"
						}
					}
				},
				"media_channels": {
					"$ref": "#/$defs/channels",
					"description": "A list of channel ids where only media is allowed."
				},
				"logging_channel": {
					"type": "integer",
					"description": "The id of the channel to send logs to."
				}
			}
		},
		"administrators": {
			"type": "object",
			"properties": {
				"roles": {
					"$ref": "#/$defs/roles",
					"description": "A list of role ids. Users with these roles have administrative privileges over this Discord bot."
				},
				"users": {
					"$ref": "#/$defs/users",
					"description": "A list of user ids. Users with these ids have administrative privileges over this Discord bot."
				}
			},
			"description": "The list of administrators to control the Discord bot."
		},
		"thread_introductions": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"channels": {
						"$ref": "#/$defs/channels",
						"description": "A list of channel ids. The bot will only introduce in threads under these channels."
					},
					"response": {
						"$ref": "#/$defs/response",
						"description": "The response to send when the thread has been created."
					}
				}
			},
			"description": "Introduce new threads with a message.",
			"minItems": 1,
			"uniqueItems": true
		},
		"message_responses": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"includes": {
						"type": "object",
						"channels": {
							"$ref": "#/$defs/channels",
							"description": "A list of channel ids. The bot will only respond to messages in these channels."
						},
						"match": {
							"$ref": "#/$defs/match",
							"description": "The message must match this regex to be responded to."
						}
					},
					"excludes": {
						"type": "object",
						"roles": {
							"$ref": "#/$defs/roles",
							"description": "A list of role ids. The bot will not respond to messages from users with these roles."
						},
						"match": {
							"$ref": "#/$defs/match",
							"description": "Messages matching this regex will not be responded to."
						}
					},
					"condition": {
						"type": "object",
						"properties": {
							"user": {
								"type": "object",
								"properties": {
									"server_age": {
										"type": "integer",
										"description": "The user must be less than this many days old on the server."
									}
								},
								"description": "User condition."
							}
						},
						"description": "The conditions to respond to the message."
					},
					"response": {
						"$ref": "#/$defs/response",
						"description": "The response to send when the message is responded to."
					}
				},
				"description": "The conditions to respond to a message."
			},
			"description": "A list of responses the Discord bot should send based on given conditions."
		}
	},
	"$defs": {
		"color": {
			"type": "integer",
			"description": "The color of the embed."
		},
		"users": {
			"$ref": "#/$defs/ids"
		},
		"roles": {
			"$ref": "#/$defs/ids"
		},
		"channels": {
			"$ref": "#/$defs/ids"
		},
		"ids": {
			"type": "array",
			"items": {
				"type": "integer"
			},
			"uniqueItems": true,
			"minItems": 1
		},
		"match": {
			"$ref": "#/$defs/regex",
			"description": "A list of regex strings."
		},
		"regex": {
			"type": "array",
			"items": {
				"type": "string"
			},
			"uniqueItems": true,
			"minItems": 1
		},
		"embed": {
			"type": "object",
			"properties": {
				"title": {
					"type": "string",
					"description": "The title of the embed."
				},
				"description": {
					"type": "string",
					"description": "The description of the embed."
				},
				"color": {
					"$ref": "#/$defs/color",
					"description": "The color of the embed."
				},
				"fields": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string",
								"description": "The name of the field."
							},
							"value": {
								"type": "string",
								"description": "The value of the field."
							},
							"inline": {
								"type": "boolean",
								"description": "Whether the field is inline."
							}
						},
						"description": "The field to add to the embed."
					},
					"description": "The fields to add to the embed."
				},
				"image": {
					"type": "object",
					"properties": {
						"url": {
							"type": "string",
							"description": "The url of the image."
						}
					},
					"description": "The image to add to the embed."
				},
				"thumbnail": {
					"type": "object",
					"properties": {
						"url": {
							"type": "string",
							"description": "The url of the thumbnail."
						}
					},
					"description": "The thumbnail to add to the embed."
				},
				"author": {
					"type": "object",
					"properties": {
						"name": {
							"type": "string",
							"description": "The name of the author."
						},
						"url": {
							"type": "string",
							"description": "The url of the author."
						},
						"icon_url": {
							"type": "string",
							"description": "The url of the author's icon."
						}
					},
					"description": "The author to add to the embed."
				},
				"footer": {
					"type": "object",
					"properties": {
						"text": {
							"type": "string",
							"description": "The text of the footer."
						},
						"icon_url": {
							"type": "string",
							"description": "The url of the footer's icon."
						}
					},
					"description": "The footer to add to the embed."
				}
			}
		},
		"response": {
			"type": "object",
			"properties": {
				"message": {
					"type": "string",
					"description": "The message. Can be empty if the embed is not empty"
				},
				"embed": {
					"$ref": "#/$defs/embed",
					"description": "The embed to send."
				}
			}
		}
	}
}

=== ReVanced/revanced-discord-bot/configuration.revanced.json
{
	"general": {
		"embed_color": 14908858,
		"mute": {
			"role": 953984696491061289,
			"take": [996121272897519687, 965267139902705744, 995126555867086938, 965270054633619476]
		},
		"media_channels": [954148665646260314],
		"logging_channel": 1027892160797872179
	},
	"administrators": {
		"roles": [955220417969262612],
		"users": [737323631117598811]
	},
	"thread_introductions": [
		{
			"channels": [985666124068814888],
			"response": {
				"message": "Hi. Please wait for someone to help you with your problem.\r\nUnderstand that this channel is only meant to help you.\r\nIf you encounter a bug, please report it on the respective GitHub repository instead.\r\n\r\nThank you!"
			}
		}
	],
	"message_responses": [
		{
			"includes": {
				"channels": [952946952348270626, 954147049832603748],
				"match": ["(?i)(((where|how|download|install|get|manager).*){2,})"]
			},
			"excludes": {
				"roles": [
					965267139902705744, 955220417969262612, 952987191401926697,
					1027874293192863765
				],
				"match": ["(?i)patch", "(?i)error"]
			},
			"condition": {
				"user": {
					"server_age": 120
				}
			},
			"response": {
				"embed": {
					"title": "Where or how to get ReVanced ‚ùì",
					"description": "You have asked a question that has been answered in the <#953993848374325269> channel already. Make sure to read it as it will answer a lot of your questions guaranteed.",
					"color": 14908858,
					"fields": [
						{
							"name": "üî∏ Regarding your question",
							"value": "Please refer to <#953993848374325269> `III`.",
							"inline": false
						}
					],
					"footer": {
						"text": "",
						"icon_url": ""
					},
					"image": {
						"url": ""
					},
					"thumbnail": {
						"url": "https://cdn.discordapp.com/icons/952946952348270622/d011f1dc1d27e9001d243bdedaf7443b.webp?size=512"
					},
					"author": {
						"name": "",
						"icon_url": "",
						"url": ""
					}
				}
			}
		},
		{
			"includes": {
				"channels": [952946952348270626, 954147049832603748],
				"match": ["(?i)(((error|open|patch).*){2,})"]
			},
			"excludes": {
				"roles": [
					965267139902705744, 955220417969262612, 952987191401926697,
					1027874293192863765
				],
				"match": []
			},
			"condition": {
				"user": {
					"server_age": 120
				}
			},
			"response": {
				"embed": {
					"title": "Where or how to get ReVanced ‚ùì",
					"description": "You have asked a question that has been answered in the <#953993848374325269> channel already. Make sure to read it as it will answer a lot of your questions guaranteed.",
					"color": 14908858,
					"fields": [
						{
							"name": "üî∏ Regarding your question",
							"value": "Please make sure to read the second half of <#953993848374325269> XV if you have enough knowledge, otherwise, the first half applies.",
							"inline": false
						}
					],
					"footer": {
						"text": "",
						"icon_url": ""
					},
					"image": {
						"url": ""
					},
					"thumbnail": {
						"url": "https://cdn.discordapp.com/icons/952946952348270622/d011f1dc1d27e9001d243bdedaf7443b.webp?size=512"
					},
					"author": {
						"name": "",
						"icon_url": "",
						"url": ""
					}
				}
			}
		},
		{
			"includes": {
				"channels": [952946952348270626, 954147049832603748],
				"match": ["(?i)(((sponsor|sponcer).*){1,}((no|work).*){2,})"]
			},
			"excludes": {
				"roles": [
					965267139902705744, 955220417969262612, 952987191401926697,
					1027874293192863765
				],
				"match": []
			},
			"condition": {
				"user": {
					"server_age": 120
				}
			},
			"response": {
				"embed": {
					"title": "SponsorBlock does not work ‚ùì",
					"description": "You have asked a question that has been answered in the <#953993848374325269> channel already. Make sure to read it as it will answer a lot of your questions guaranteed.",
					"color": 14908858,
					"fields": [
						{
							"name": "üî∏ Regarding your question",
							"value": "Please refer to <#953993848374325269> XXX.",
							"inline": false
						}
					],
					"footer": {
						"text": "",
						"icon_url": ""
					},
					"image": {
						"url": ""
					},
					"thumbnail": {
						"url": "https://cdn.discordapp.com/icons/952946952348270622/d011f1dc1d27e9001d243bdedaf7443b.webp?size=512"
					},
					"author": {
						"name": "",
						"icon_url": "",
						"url": ""
					}
				}
			}
		},
		{
			"includes": {
				"channels": [952946952348270626, 954147049832603748],
				"match": ["vanced\\s*\\.io"]
			},
			"excludes": {
				"roles": [
					965267139902705744, 955220417969262612, 952987191401926697,
					1027874293192863765
				],
				"match": []
			},
			"condition": {
				"user": {
					"server_age": 365
				}
			},
			"response": {
				"embed": {
					"title": "What are the official links of ReVanced‚ùì",
					"description": "A list of official links can be found in <#954066838856273960>.",
					"color": 14908858,
					"fields": [
						{
							"name": "üî∏ Regarding your question",
							"value": "ReVanced is always available at [revanced.app](https://revanced.app).",
							"inline": false
						}
					],
					"footer": {
						"text": "",
						"icon_url": ""
					},
					"image": {
						"url": ""
					},
					"thumbnail": {
						"url": "https://cdn.discordapp.com/icons/952946952348270622/d011f1dc1d27e9001d243bdedaf7443b.webp?size=512"
					},
					"author": {
						"name": "",
						"icon_url": "",
						"url": ""
					}
				}
			}
		}
	]
}
